name: shaghlny
description: SHAGHLNY Service Marketplace
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  google_sign_in: ^6.1.6
  google_maps_flutter: ^2.6.0
  geolocator: ^10.1.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  uuid: ^4.3.3
  provider: ^6.1.1
  cupertino_icons: ^1.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  